name: Vercel Production Deployment
on:
  push:
    branches:
      - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        concurrency: Production
        environment:
            name: Production
            url: ${{ steps.get_release_url.outputs.release_url }}
        steps:
        - uses: actions/checkout@v4
        - name: Install Vercel CLI
          run: npm install -g vercel
        - name: Link Vercel Project
          run: vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{vars.VERCEL_PROJECT}} --yes
        - name: Deploy with Vercel
          run: vercel deploy --prod --token=${{secrets.VERCEL_TOKEN}} >deployment-url.txt 2>error.txt
        - name: Set release url
          id: get_release_url
          run: echo release_url=$(cat deployment-url.txt) >> $GITHUB_OUTPUT