name: Vercel Preview Deployment
on:
  pull_request:
    branches:
      - main
jobs:
    deployment:
        runs-on: ubuntu-latest
        concurrency: Preview
        environment:
            name: Preview
            url: ${{ steps.get_release_url.outputs.release_url }}
        steps:
        - uses: actions/checkout@v4
        - name: Install Vercel CLI
          run: npm install -g vercel
        - name: Link Vercel Project
          run: vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{secrets.VERCEL_PROJECT}} --yes
        - name: Deploy with Vercel
          run: vercel deploy --target=staging --token=${{secrets.VERCEL_TOKEN}} >deployment-url.txt 2>error.txt
        - name: Set release url
          id: get_release_url
          run: echo release_url=$(cat deployment-url.txt) >> $GITHUB_OUTPUT
        - name: Comment on PR
          run: |
            cat  << EOF > comment.md
            ## :rocket: Preview Deployment
            [Preview Deployment](${{ steps.get_release_url.outputs.release_url }})
            EOF
            gh pr comment ${{ github.event.number }} --body-file comment.md
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}